# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  	config.vm.box = "centos64-minimal"
  	config.vm.box_url = "https://dl.dropboxusercontent.com/u/217341/vagrant/CentOS-6.4-x86_64-v20130731.box"

  	config.vm.network :private_network, ip: "192.168.33.99"

  	# 2Gb are highly advisable
	config.vm.provider :virtualbox do |v|
  		v.memory = 2048
	end  	

	config.vm.provision "shell", path: "./provisioning/go-server.sh"
end