Vagrant::Config.run do |config|
  config.vm.box = "centos63-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/217341/vagrant/CentOS-6.3-x86_64-v20130101.box"

  config.vm.network :hostonly, "192.168.33.81"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "init.pp"
    puppet.module_path    = "modules"
  end

end
