Vagrant::Config.run do |config|
  config.vm.box = "centos64-minimal"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/217341/vagrant/CentOS-6.4-x86_64-v20130731.box"

  config.vm.network :hostonly, "192.168.33.99"
end
